spring:

  main:
    allow-bean-definition-overriding: true

  application:
    name: pep-iot
  profiles:
    active: ${env:dev}
server:
  port: 6969
  servlet:
    context-path: /pep

logging:
  #  config: classpath:logback-spring.xml
  level:
    root: info
    com.example.pep.iot.business: debug
    com.example.pep.iot.emq.mapper: debug
    io.lettuce.core.protocol: info
    

mybatis-plus:
  global-config:
    db-config:
      # 全局逻辑删除的实体字段名
      logic-delete-field: isDeleted
      # 逻辑已删除值(默认为 true)
      logic-delete-value: true
      # 逻辑未删除值(默认为 false)
      logic-not-delete-value: false

