spring:
  application:
    name: pep-iot
  profiles:
    active: ${env:dev}
server:
  port: 6969
  servlet:
    context-path: /pep

logging:
  #  config: classpath:logback-spring.xml
  level:
    root: info
    com.example.pep.iot.business: debug
    com.example.pep.iot.emq.mapper: debug

