#开发配置
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3366/pep-iot
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    continue-on-error: true
  elasticsearch:
    rest:
      uris: localhost:9200
  redis:
    database: 0
    host: localhost

  kafka:
    bootstrap-servers: localhost:9092
    listener:
      type: batch
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: default
      enable-auto-commit: true
      auto-commit-interval: 5s
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


pep:
  emq:
    username: admin
    password: public
    http-url: http://localhost:18083
    client-auth-url: /api/v3/auth_clientid
    keepAlive: 60
    mqtt:
      # mqtt://
      mqttUrl: localhost
      port: 1883


